### ISSUE TITLE
change theme and refresh

### ISSUE THREAD

**Issue by chanthavong** [productdevbook/oku-nuxt3-template#110]
### Environment

nuxt: 3 stable

### Describe the bug

![image](https://user-images.githubusercontent.com/18229355/203989411-3e7b7d06-4a47-4df2-a028-8a5066cc98d6.png)

**Comment by productdevbook** [comment]
I see Apollo installations. Does this pure this project give the same error?

**Comment by productdevbook** [comment]
https://twitter.com/productdevbook/status/1606198773583171584

I published the library for Apollo. There are 3 steps to nuxt there.
